### ISSUE TITLE
Dependency on bitsra

### ISSUE THREAD

**Issue by parekhpravesh** [precimed/mostest#11]
When running the mostest demo the first time, there is an error on line 20 of `PlinkRead_binary2` where there is a dependency on `bitsra` function from the Fixed-Point Designer toolbox. The specific error message is below:

```
'bitsra' requires Fixed-Point Designer.

Error in PlinkRead_binary2 (line 20)
indvec(j) = bitand(bitsra(ishift, shiftind(j)),3) ;

Error in mostest (line 112)
geno_int8 = PlinkRead_binary2(nsubj, i:j, bfile);
```

**Comment by ofrei** [comment]
@parekhpravesh Thanks! This should now be fixed in master branch, see https://github.com/precimed/mostest/commit/2ce17d90af163ad9e3b096b5e01a3e926a2b6fe6 . This hardcodes ``geno_values``, as it's a fixed 256x4 array (independent of input data). For more info about .bed file format see https://www.cog-genomics.org/plink/1.9/formats#bed .
